In [45]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [46]:
train = pd.read_csv('/content/drive/My Drive/BT4012 Group 06/Data/train_non_embedded.csv', index_col=None)
test = pd.read_csv('/content/drive/My Drive/BT4012 Group 06/Data/test_non_embedded.csv', index_col=None)
X_train = train.drop('fraudulent',axis = 1)
y_train = train[['fraudulent']]
X_test = test.drop('fraudulent',axis = 1)
y_test = test[['fraudulent']]

Linear SVM

In [47]:
model1 = SVC(kernel='linear', C=1.0)
model1.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [48]:
y_pred1 = model1.predict(X_test)
accuracy1 = accuracy_score(y_test, y_pred1)
accuracy1

0.9549776286353467

In [49]:
feature_coefficients = model1.coef_
feature_coefficients

array([[-0.00357328, -0.04214854, -0.02130924, -0.00930354, -0.00717225,
         0.03352622, -0.01794684,  0.22446977,  2.37939656, -0.07658829,
         0.10614103, -0.03708079,  0.29374222, -0.04298651,  0.11018494,
         0.07624515,  0.10699207, -0.18956455, -0.02596716,  0.07269463,
        -0.30135297,  0.21347002, -0.33021431, -0.16910111, -0.25449247,
         0.15689213,  0.08608874, -0.30628633,  0.00594714, -0.02021908,
         0.27113091,  0.00469796,  0.03024044, -0.07191238, -0.00936121,
         0.01441787, -0.1884348 ,  0.05226284,  0.07241066,  0.10030087,
         0.10338998, -0.25245833, -0.13001896, -0.12326265,  0.43154284,
         0.03206713, -0.05818209,  0.08967664,  0.13597277, -0.07840784,
         0.09711234, -0.00342001,  0.00584337,  0.09453391, -0.15572678,
         0.02868795, -0.0985295 ,  0.03627808,  0.29874785, -0.24178643,
         0.76550791, -0.01943749,  0.00283807,  0.01059181,  0.02937411,
        -0.02336651,  0.0433694 , -0.01705217, -0.0

In [50]:
len(feature_coefficients[0])

74

In [51]:
abs_feature_coefficients = np.abs(feature_coefficients)

sorted_indices = np.argsort(abs_feature_coefficients, axis=None)[::-1]

top_10_indices1 = sorted_indices[:10]

top_10_columns1 = train.columns[top_10_indices1 ]

top_10_coefficient1= feature_coefficients[0][top_10_indices1]

In [52]:
print(top_10_columns1)
print(top_10_coefficient1)

Index(['department_mean_target', 'country_ratio', 'adjs_vs_length_benefits',
       'fraudulent', 'verbs_vs_words_company_profile',
       'num_of_verbs_requirements', 'nouns_vs_length_benefits',
       'country_total_number', 'num_of_nouns_description',
       'num_of_verbs_benefits'],
      dtype='object')
[ 2.37939656  0.76550791  0.43154284 -0.36796415 -0.33021431 -0.30628633
 -0.30135297  0.29874785  0.29374222  0.27113091]


Polynomial

In [53]:
model2 = SVC(kernel='poly', C=1.0)
model2.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='poly')

In [54]:
y_pred2 = model2.predict(X_test)
accuracy2 = accuracy_score(y_test, y_pred2)
accuracy2

0.9605704697986577

In [55]:
support_vectors = model2.support_vectors_
dual_coefficients = model2.dual_coef_

In [56]:
support_vectors

array([[0.  , 0.  , 0.  , ..., 0.1 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.1 , 0.  , 0.  ],
       [0.  , 1.  , 1.  , ..., 0.14, 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.1 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.1 , 0.  , 0.  ],
       [0.  , 1.  , 0.  , ..., 0.1 , 0.  , 0.  ]])

In [57]:
dual_coefficients

array([[-1.        , -1.        , -0.17317076, ...,  1.        ,
         1.        ,  1.        ]])

In [58]:
max_dual_coefficient = np.max(model2.dual_coef_)
max_dual_coefficient_index = np.argmax(model2.dual_coef_)
corresponding_support_vector = model2.support_vectors_[max_dual_coefficient_index]

In [59]:
corresponding_support_vector

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.875     , 0.67568512, 0.0445939 , 0.        ,
       0.        , 0.        , 0.02415459, 0.6       , 0.15151515,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02777778,
       0.2       , 0.05050505, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01818182, 1.        ,
       0.33333333, 0.01075269, 0.12      , 0.03030303, 0.00636943,
       1.        , 0.33333333, 0.01612903, 1.        , 0.33333333,
       0.        , 0.        , 0.        , 0.00406504, 0.04      ,
       0.01010101, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.25397382, 0.05954466,
       0.01563937, 0.        , 1.        , 0.        , 0.        ,
       0.        , 0.60710291, 0.74210011, 0.36849832, 0.45651566,
       0.07      , 0.1       , 0.        , 0.        ])

In [60]:
abs_corresponding_support_vector = np.abs(corresponding_support_vector)

sorted_indices = np.argsort(abs_corresponding_support_vector, axis=None)[::-1]

top_10_indices2 = sorted_indices[:10]

top_10_columns2 = train.columns[top_10_indices2 ]

top_10_coefficient2= corresponding_support_vector[top_10_indices2]


In [61]:
print(top_10_columns2)
print(top_10_coefficient2)

Index(['adjs_vs_words_benefits', 'adjs_vs_words_requirements',
       'employment_type_Full-time', 'adjs_vs_words_company_profile',
       'sentiment score_description', 'education_frequency',
       'department_frequency', 'experience_frequency',
       'nouns_vs_words_description', 'function_frequency'],
      dtype='object')
[1.         1.         1.         1.         0.875      0.74210011
 0.67568512 0.60710291 0.6        0.45651566]


Sigmoid

In [62]:
model3 = SVC(kernel='sigmoid', C=1.0)
model3.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='sigmoid')

In [63]:
y_pred3 = model3.predict(X_test)
accuracy3 = accuracy_score(y_test, y_pred3)
accuracy3

0.9379194630872483

In [64]:
max_dual_coefficient = np.max(model3.dual_coef_)
max_dual_coefficient_index = np.argmax(model3.dual_coef_)
corresponding_support_vector = model3.support_vectors_[max_dual_coefficient_index]

In [65]:
abs_corresponding_support_vector = np.abs(corresponding_support_vector)

sorted_indices = np.argsort(abs_corresponding_support_vector, axis=None)[::-1]

top_10_indices3 = sorted_indices[:10]

top_10_columns3 = train.columns[top_10_indices3 ]

top_10_coefficient3 = corresponding_support_vector[top_10_indices3]


In [66]:
print(top_10_columns3)
print(top_10_coefficient3)

Index(['department_mean_target', 'has_company_logo', 'country_total_number',
       'country_fraudulent', 'employment_type_Full-time', 'has_questions',
       'sentiment score_profile', 'sentiment score_benefits',
       'sentiment score_description', 'sentiment score_requirement'],
      dtype='object')
[1.     1.     1.     1.     1.     1.     0.9771 0.9633 0.9432 0.93  ]


RBF

In [67]:
model4 = SVC(kernel='rbf', C=1.0)
model4.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [68]:
y_pred4 = model4.predict(X_test)
accuracy4 = accuracy_score(y_test, y_pred4)
accuracy4

0.95917225950783

In [69]:
max_dual_coefficient = np.max(model4.dual_coef_)
max_dual_coefficient_index = np.argmax(model4.dual_coef_)
corresponding_support_vector = model4.support_vectors_[max_dual_coefficient_index]

In [70]:
abs_corresponding_support_vector = np.abs(corresponding_support_vector)

sorted_indices = np.argsort(abs_corresponding_support_vector, axis=None)[::-1]

top_10_indices4 = sorted_indices[:10]

top_10_columns4 = train.columns[top_10_indices4 ]

top_10_coefficient4 = corresponding_support_vector[top_10_indices4]


In [71]:
print(top_10_columns4)
print(top_10_coefficient4)

Index(['adjs_vs_words_benefits', 'adjs_vs_words_requirements',
       'employment_type_Full-time', 'adjs_vs_words_company_profile',
       'sentiment score_description', 'education_frequency',
       'department_frequency', 'experience_frequency',
       'nouns_vs_words_description', 'function_frequency'],
      dtype='object')
[1.         1.         1.         1.         0.875      0.74210011
 0.67568512 0.60710291 0.6        0.45651566]


In [72]:
print("The accuracy for linear SVM:", accuracy1)
print("The accuracy for polynomical SVM:", accuracy2)
print("The accuracy for sigmoid SVM:", accuracy3)
print("The accuracy for rbf SVM:", accuracy4)

The accuracy for linear SVM: 0.9549776286353467
The accuracy for polynomical SVM: 0.9605704697986577
The accuracy for sigmoid SVM: 0.9379194630872483
The accuracy for rbf SVM: 0.95917225950783
